name: Build Windows EXE & Create Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "no requirements"
          pip install pyinstaller==6.15.0

      - name: Build EXE
        run: |
          pyinstaller --onefile --noconsole --name mdi_autologin --version-file version_file.txt app.py
          dir dist

      - name: Package ZIP
        run: |
          mkdir release
          powershell -Command "Compress-Archive -Path .\dist\mdi_autologin.exe -DestinationPath .\release\mdi_autologin-${{ github.ref_name }}.zip -Force"

      - name: Install NSIS
        run: choco install nsis -y
        shell: pwsh

      - name: Build NSIS installer
        run: |
          makensis installer.nsi
          move mdi_autologin_installer.exe release\mdi_autologin_installer-${{ github.ref_name }}.exe
        shell: pwsh

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: "MDI AutoLogin ${{ github.ref_name }}"
          body: "Automated build."
          artifacts: "release/*"
